steps:
  # Build the Docker image tagged with commit SHA
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','us-central1-docker.pkg.dev/$PROJECT_ID/dead-simpl-frontend/dead-simpl-frontend:$SHORT_SHA','.' ]

  # Optionally tag the image with branch name (for non-PR builds)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        if [ -n "$$BRANCH_NAME" ]; then \
          SAFE_TAG=$(echo "$$BRANCH_NAME" | tr '/_' '--' | tr -cd '[:alnum:].-'); \
          docker tag us-central1-docker.pkg.dev/$PROJECT_ID/dead-simpl-frontend/dead-simpl-frontend:$SHORT_SHA \
                     us-central1-docker.pkg.dev/$PROJECT_ID/dead-simpl-frontend/dead-simpl-frontend:"$$SAFE_TAG"; \
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/dead-simpl-frontend/dead-simpl-frontend:"$$SAFE_TAG"; \
        fi

  # Push the commit-tagged image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','us-central1-docker.pkg.dev/$PROJECT_ID/dead-simpl-frontend/dead-simpl-frontend:$SHORT_SHA']

  # Create a Cloud Deploy release against the unified pipeline
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'deploy'
      - 'releases'
      - 'create'
      - 'frontend-$SHORT_SHA'
      - '--delivery-pipeline=dead-simpl'
      - '--region=us-central1'
      - '--source=.'
      - '--images=us-central1-docker.pkg.dev/halogen-eon-470613-h3/dead-simpl-frontend/dead-simpl-frontend=us-central1-docker.pkg.dev/$PROJECT_ID/dead-simpl-frontend/dead-simpl-frontend:$SHORT_SHA'

# Store build artifacts
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/dead-simpl-frontend/dead-simpl-frontend:$SHORT_SHA'

# Build timeout
timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
